spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question_platform
    username: root
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate


jwt:
  issuer: auth
  access-expiration-in-ms: 18000000
  alias: prgxKey
  certificate: prgxKey.jks
  store-password: prgxpass
  key-password: prgxpass
  secret: 68?Rctu2?_p}Hh8}&=|j!dSVh,en).=SQA6&U+BSx/Fhs84kdg5.V'y;G8Es.9S8NH9Th}~8Bd4yc_Mi